const QUERIES = {
  USERS_LIST: 'users-list',
  CATEGORIES_LIST:'categories-list',
  ARCHIVED_CATEGORIES_LIST:'archived-categories-list',
  SUB_CATEGORIES_LIST:'sub-categories-list',
  ARCHIVED_SUB_CATEGORIES_LIST:'archived-sub-categories-list',
  CHILD_SUB_CATEGORIES_LIST:'child-sub-categories-list',
  ARCHIVED_CHILD_SUB_CATEGORIES_LIST:'archived-child-sub-categories-list',
  BRNACHES_LIST:'branches-list',
  ARCHIVED_BRNACHES_LIST:'archived-branches-list',
  GROUPS_LIST:'groups-list',
  ARCHIVED_GROUPS_LIST:'archived-groups-list',
  OPTIONS_LIST:'options-list',
  ARCHIVED_OPTIONS_LIST:'archived-options-list',
  TYPES_LIST:'types-list',
  ARCHIVED_TYPES_LIST:'archived-types-list',
  EXTRAS_LIST:'extras-list',
  ARCHIVED_EXTRAS_LIST:'archived-extras-list',
  PRODUCTS_LIST:'products-list',
  ARCHIVED_PRODUCTS_LIST:'archived-products-list',
  PERMISSIONS_LIST:'permissions-list',
  ARCHIVED_PERMISSIONS_LIST:'archived-permissions-list',
  ROLES_LIST:'roles-list',
  ARCHIVED_ROLES_LIST:'archived-roles-list',
}

export {QUERIES}
